[package]
name = "attestation-exported-authenticators"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.23.5", default-features = false, features = ["std"] }
x509-parser = "0.18.0"

[dev-dependencies]
quinn = "0.11.9"
rcgen = "0.14.3"
tokio = { version = "1.28.1", features = ["full"] }
tdx-quote = { version = "0.0.3", features = ["mock"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
